apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  SQS_QUEUE_URL: {{ .Values.config.sqsQueueUrl | quote }}
  CLUSTER_NAME: {{ .Values.config.clusterName | quote }}
  LOG_LEVELS: {{ .Values.config.logLevels | quote }}
  KARPENTER_NAMESPACE: {{ .Values.config.karpenterNamespace | quote }}
  KARPENTER_LABEL_SELECTOR: {{ .Values.config.karpenterLabelSelector | quote }}
