apiVersion: v2
name: karpenter-pulse
description: Umbrella Helm chart orchestrating Karpenter Pulse frontend and backend deployments.
type: application
version: 1.0.3
appVersion: "karpenter-pulse-v1.0.0"
